"""Initial schema

Revision ID: 001
Create Date: 2024-01-01
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSONB

revision = "001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Users
    op.create_table("users",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.String(255), unique=True, nullable=False),
        sa.Column("username", sa.String(100), unique=True, nullable=False),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("full_name", sa.String(255), nullable=False),
        sa.Column("role", sa.String(50), default="viewer"),
        sa.Column("avatar_url", sa.String(500)),
        sa.Column("is_active", sa.Boolean, default=True),
        sa.Column("is_verified", sa.Boolean, default=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # Teams
    op.create_table("teams",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("short_name", sa.String(10), nullable=False),
        sa.Column("logo_url", sa.String(500)),
        sa.Column("primary_color", sa.String(7), default="#0066CC"),
        sa.Column("secondary_color", sa.String(7), default="#FFFFFF"),
        sa.Column("cap_color", sa.String(20), default="dark"),
        sa.Column("city", sa.String(100)),
        sa.Column("country", sa.String(100)),
        sa.Column("division", sa.String(100)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # Team memberships
    op.create_table("team_memberships",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("team_id", UUID(as_uuid=True), sa.ForeignKey("teams.id"), nullable=False),
        sa.Column("role", sa.String(50), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # Seasons & Tournaments
    op.create_table("seasons",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("team_id", UUID(as_uuid=True), sa.ForeignKey("teams.id"), nullable=False),
        sa.Column("start_year", sa.Integer, nullable=False),
        sa.Column("end_year", sa.Integer, nullable=False),
        sa.Column("is_active", sa.Boolean, default=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table("tournaments",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("season_id", UUID(as_uuid=True), sa.ForeignKey("seasons.id")),
        sa.Column("location", sa.String(255)),
        sa.Column("start_date", sa.DateTime(timezone=True)),
        sa.Column("end_date", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # Players
    op.create_table("players",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", UUID(as_uuid=True), sa.ForeignKey("users.id")),
        sa.Column("team_id", UUID(as_uuid=True), sa.ForeignKey("teams.id"), nullable=False),
        sa.Column("first_name", sa.String(100), nullable=False),
        sa.Column("last_name", sa.String(100), nullable=False),
        sa.Column("cap_number", sa.Integer, nullable=False),
        sa.Column("position", sa.String(50), default="utility"),
        sa.Column("date_of_birth", sa.Date),
        sa.Column("height_cm", sa.Integer),
        sa.Column("weight_kg", sa.Float),
        sa.Column("dominant_hand", sa.String(10), default="right"),
        sa.Column("nationality", sa.String(100)),
        sa.Column("photo_url", sa.String(500)),
        sa.Column("is_active", sa.Boolean, default=True),
        sa.Column("is_captain", sa.Boolean, default=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # Cameras
    op.create_table("cameras",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("camera_type", sa.String(50), nullable=False),
        sa.Column("stream_url", sa.String(1000)),
        sa.Column("venue", sa.String(255)),
        sa.Column("position", sa.String(100)),
        sa.Column("settings", JSONB),
        sa.Column("is_active", sa.Boolean, default=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # Matches
    op.create_table("matches",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("home_team_id", UUID(as_uuid=True), sa.ForeignKey("teams.id"), nullable=False),
        sa.Column("away_team_id", UUID(as_uuid=True), sa.ForeignKey("teams.id"), nullable=False),
        sa.Column("tournament_id", UUID(as_uuid=True), sa.ForeignKey("tournaments.id")),
        sa.Column("season_id", UUID(as_uuid=True), sa.ForeignKey("seasons.id")),
        sa.Column("status", sa.String(50), default="scheduled"),
        sa.Column("scheduled_at", sa.DateTime(timezone=True)),
        sa.Column("started_at", sa.DateTime(timezone=True)),
        sa.Column("ended_at", sa.DateTime(timezone=True)),
        sa.Column("home_score", sa.Integer, default=0),
        sa.Column("away_score", sa.Integer, default=0),
        sa.Column("venue", sa.String(255)),
        sa.Column("pool_length", sa.Float, default=30.0),
        sa.Column("pool_width", sa.Float, default=20.0),
        sa.Column("period_duration", sa.Integer, default=480),
        sa.Column("shot_clock", sa.Integer, default=30),
        sa.Column("notes", sa.Text),
        sa.Column("metadata_json", JSONB),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # Match events
    op.create_table("match_events",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("match_id", UUID(as_uuid=True), sa.ForeignKey("matches.id"), nullable=False),
        sa.Column("event_type", sa.String(50), nullable=False),
        sa.Column("period", sa.String(10), nullable=False),
        sa.Column("timestamp_ms", sa.Integer, nullable=False),
        sa.Column("game_clock_seconds", sa.Integer),
        sa.Column("player_id", UUID(as_uuid=True), sa.ForeignKey("players.id")),
        sa.Column("secondary_player_id", UUID(as_uuid=True), sa.ForeignKey("players.id")),
        sa.Column("team_id", UUID(as_uuid=True), sa.ForeignKey("teams.id")),
        sa.Column("position_x", sa.Float),
        sa.Column("position_y", sa.Float),
        sa.Column("details", JSONB),
        sa.Column("is_auto_detected", sa.Boolean, default=True),
        sa.Column("confidence", sa.Float),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_match_events_match_id", "match_events", ["match_id"])
    op.create_index("ix_match_events_timestamp", "match_events", ["timestamp_ms"])

    # Videos
    op.create_table("videos",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("match_id", UUID(as_uuid=True), sa.ForeignKey("matches.id")),
        sa.Column("camera_id", UUID(as_uuid=True), sa.ForeignKey("cameras.id")),
        sa.Column("uploaded_by", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("description", sa.String(1000)),
        sa.Column("source", sa.String(50), default="upload"),
        sa.Column("source_url", sa.String(2000)),
        sa.Column("status", sa.String(50), default="uploading"),
        sa.Column("original_filename", sa.String(500)),
        sa.Column("storage_path", sa.String(1000)),
        sa.Column("hls_path", sa.String(1000)),
        sa.Column("thumbnail_path", sa.String(1000)),
        sa.Column("file_size_bytes", sa.BigInteger),
        sa.Column("duration_seconds", sa.Float),
        sa.Column("width", sa.Integer),
        sa.Column("height", sa.Integer),
        sa.Column("fps", sa.Float),
        sa.Column("codec", sa.String(50)),
        sa.Column("bitrate", sa.Integer),
        sa.Column("is_stabilized", sa.Boolean, default=False),
        sa.Column("is_panoramic", sa.Boolean, default=False),
        sa.Column("camera_angle", sa.String(50)),
        sa.Column("processing_progress", sa.Float, default=0.0),
        sa.Column("processing_error", sa.String(1000)),
        sa.Column("processing_metadata", JSONB),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("processed_at", sa.DateTime(timezone=True)),
    )

    # Clips
    op.create_table("clips",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("match_id", UUID(as_uuid=True), sa.ForeignKey("matches.id"), nullable=False),
        sa.Column("video_id", UUID(as_uuid=True), sa.ForeignKey("videos.id"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("event_id", UUID(as_uuid=True), sa.ForeignKey("match_events.id")),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("description", sa.Text),
        sa.Column("start_ms", sa.Integer, nullable=False),
        sa.Column("end_ms", sa.Integer, nullable=False),
        sa.Column("duration_ms", sa.Integer, nullable=False),
        sa.Column("keyframes", JSONB),
        sa.Column("follow_player_id", UUID(as_uuid=True), sa.ForeignKey("players.id")),
        sa.Column("follow_ball", sa.Boolean, default=False),
        sa.Column("exported_path", sa.String(1000)),
        sa.Column("thumbnail_path", sa.String(1000)),
        sa.Column("is_exported", sa.Boolean, default=False),
        sa.Column("export_quality", sa.String(20), default="1080p"),
        sa.Column("is_public", sa.Boolean, default=False),
        sa.Column("share_token", sa.String(64), unique=True),
        sa.Column("is_auto_generated", sa.Boolean, default=False),
        sa.Column("ability_labels", JSONB),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # Clip tags & annotations
    op.create_table("clip_tags",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("clip_id", UUID(as_uuid=True), sa.ForeignKey("clips.id"), nullable=False),
        sa.Column("tag", sa.String(100), nullable=False),
    )
    op.create_table("annotations",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("clip_id", UUID(as_uuid=True), sa.ForeignKey("clips.id"), nullable=False),
        sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("annotation_type", sa.String(50), nullable=False),
        sa.Column("timestamp_ms", sa.Integer, nullable=False),
        sa.Column("duration_ms", sa.Integer, default=3000),
        sa.Column("data", JSONB, nullable=False),
        sa.Column("color", sa.String(7), default="#FF0000"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # Analytics tables
    op.create_table("match_analytics",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("match_id", UUID(as_uuid=True), sa.ForeignKey("matches.id"), unique=True, nullable=False),
        sa.Column("home_possession_pct", sa.Float, default=50.0),
        sa.Column("away_possession_pct", sa.Float, default=50.0),
        sa.Column("possession_timeline", JSONB),
        sa.Column("home_shots", sa.Integer, default=0),
        sa.Column("away_shots", sa.Integer, default=0),
        sa.Column("home_shots_on_target", sa.Integer, default=0),
        sa.Column("away_shots_on_target", sa.Integer, default=0),
        sa.Column("home_power_play_attempts", sa.Integer, default=0),
        sa.Column("home_power_play_goals", sa.Integer, default=0),
        sa.Column("away_power_play_attempts", sa.Integer, default=0),
        sa.Column("away_power_play_goals", sa.Integer, default=0),
        sa.Column("home_exclusions", sa.Integer, default=0),
        sa.Column("away_exclusions", sa.Integer, default=0),
        sa.Column("momentum_timeline", JSONB),
        sa.Column("quarter_stats", JSONB),
        sa.Column("ai_summary", sa.String(5000)),
        sa.Column("ai_talking_points", JSONB),
        sa.Column("ai_recommendations", JSONB),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table("player_match_stats",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("match_id", UUID(as_uuid=True), sa.ForeignKey("matches.id"), nullable=False),
        sa.Column("player_id", UUID(as_uuid=True), sa.ForeignKey("players.id"), nullable=False),
        sa.Column("team_id", UUID(as_uuid=True), sa.ForeignKey("teams.id"), nullable=False),
        sa.Column("goals", sa.Integer, default=0),
        sa.Column("assists", sa.Integer, default=0),
        sa.Column("shots", sa.Integer, default=0),
        sa.Column("shots_on_target", sa.Integer, default=0),
        sa.Column("saves", sa.Integer, default=0),
        sa.Column("exclusions_drawn", sa.Integer, default=0),
        sa.Column("exclusions_committed", sa.Integer, default=0),
        sa.Column("steals", sa.Integer, default=0),
        sa.Column("turnovers", sa.Integer, default=0),
        sa.Column("power_play_goals", sa.Integer, default=0),
        sa.Column("blocks", sa.Integer, default=0),
        sa.Column("sprints", sa.Integer, default=0),
        sa.Column("distance_swum_m", sa.Float, default=0.0),
        sa.Column("minutes_played", sa.Float, default=0.0),
        sa.Column("heatmap_data", JSONB),
    )
    op.create_table("shot_records",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("match_id", UUID(as_uuid=True), sa.ForeignKey("matches.id"), nullable=False),
        sa.Column("player_id", UUID(as_uuid=True), sa.ForeignKey("players.id")),
        sa.Column("event_id", UUID(as_uuid=True), sa.ForeignKey("match_events.id")),
        sa.Column("period", sa.String(5), nullable=False),
        sa.Column("timestamp_ms", sa.Integer, nullable=False),
        sa.Column("shot_x", sa.Float, nullable=False),
        sa.Column("shot_y", sa.Float, nullable=False),
        sa.Column("target_x", sa.Float),
        sa.Column("target_y", sa.Float),
        sa.Column("outcome", sa.String(20), nullable=False),
        sa.Column("shot_type", sa.String(50)),
        sa.Column("is_power_play", sa.Boolean, default=False),
        sa.Column("is_penalty", sa.Boolean, default=False),
        sa.Column("speed_kmh", sa.Float),
    )

    # Subscriptions
    op.create_table("subscription_plans",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("tier", sa.String(50), unique=True, nullable=False),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("description", sa.String(500), nullable=False),
        sa.Column("price_monthly", sa.Float, nullable=False),
        sa.Column("price_semiannual", sa.Float, nullable=False),
        sa.Column("price_annual", sa.Float, nullable=False),
        sa.Column("price_biannual", sa.Float, nullable=False),
        sa.Column("max_videos_per_month", sa.Integer, default=5),
        sa.Column("max_storage_gb", sa.Integer, default=50),
        sa.Column("can_download", sa.Boolean, default=False),
        sa.Column("has_drawing_tools", sa.Boolean, default=False),
        sa.Column("has_analytics", sa.Boolean, default=False),
        sa.Column("has_coach_assist", sa.Boolean, default=False),
        sa.Column("has_player_spotlight", sa.Boolean, default=False),
        sa.Column("has_live_streaming", sa.Boolean, default=False),
        sa.Column("max_cameras", sa.Integer, default=1),
        sa.Column("has_multi_camera", sa.Boolean, default=False),
        sa.Column("has_export_social", sa.Boolean, default=False),
        sa.Column("has_api_access", sa.Boolean, default=False),
    )
    op.create_table("subscriptions",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", UUID(as_uuid=True), sa.ForeignKey("users.id"), unique=True, nullable=False),
        sa.Column("plan_id", UUID(as_uuid=True), sa.ForeignKey("subscription_plans.id"), nullable=False),
        sa.Column("billing_cycle", sa.String(20), default="monthly"),
        sa.Column("stripe_subscription_id", sa.String(255)),
        sa.Column("stripe_customer_id", sa.String(255)),
        sa.Column("is_active", sa.Boolean, default=True),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("expires_at", sa.DateTime(timezone=True)),
        sa.Column("cancelled_at", sa.DateTime(timezone=True)),
    )

    # Lineups
    op.create_table("lineups",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("match_id", UUID(as_uuid=True), sa.ForeignKey("matches.id"), nullable=False),
        sa.Column("team_id", UUID(as_uuid=True), sa.ForeignKey("teams.id"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table("lineup_entries",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("lineup_id", UUID(as_uuid=True), sa.ForeignKey("lineups.id"), nullable=False),
        sa.Column("player_id", UUID(as_uuid=True), sa.ForeignKey("players.id"), nullable=False),
        sa.Column("cap_number", sa.Integer, nullable=False),
        sa.Column("position", sa.String(50)),
        sa.Column("is_starter", sa.Boolean, default=True),
        sa.Column("is_captain", sa.Boolean, default=False),
        sa.Column("is_mvp", sa.Boolean, default=False),
    )

    # Player stats
    op.create_table("player_stats",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("player_id", UUID(as_uuid=True), sa.ForeignKey("players.id"), nullable=False),
        sa.Column("season_id", UUID(as_uuid=True), sa.ForeignKey("seasons.id")),
        sa.Column("matches_played", sa.Integer, default=0),
        sa.Column("goals", sa.Integer, default=0),
        sa.Column("assists", sa.Integer, default=0),
        sa.Column("shots", sa.Integer, default=0),
        sa.Column("shots_on_target", sa.Integer, default=0),
        sa.Column("saves", sa.Integer, default=0),
        sa.Column("exclusions_drawn", sa.Integer, default=0),
        sa.Column("exclusions_committed", sa.Integer, default=0),
        sa.Column("steals", sa.Integer, default=0),
        sa.Column("turnovers", sa.Integer, default=0),
        sa.Column("power_play_goals", sa.Integer, default=0),
        sa.Column("penalty_goals", sa.Integer, default=0),
        sa.Column("penalty_attempts", sa.Integer, default=0),
        sa.Column("minutes_played", sa.Float, default=0.0),
        sa.Column("distance_swum_m", sa.Float, default=0.0),
        sa.Column("sprint_count", sa.Integer, default=0),
        sa.Column("abilities", JSONB),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # Heatmap data
    op.create_table("heatmap_data",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("match_id", UUID(as_uuid=True), sa.ForeignKey("matches.id"), nullable=False),
        sa.Column("player_id", UUID(as_uuid=True), sa.ForeignKey("players.id")),
        sa.Column("team_id", UUID(as_uuid=True), sa.ForeignKey("teams.id")),
        sa.Column("period", sa.String(5)),
        sa.Column("grid_data", JSONB, nullable=False),
        sa.Column("resolution_x", sa.Integer, default=30),
        sa.Column("resolution_y", sa.Integer, default=20),
    )
    op.create_table("pass_records",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("match_id", UUID(as_uuid=True), sa.ForeignKey("matches.id"), nullable=False),
        sa.Column("from_player_id", UUID(as_uuid=True), sa.ForeignKey("players.id")),
        sa.Column("to_player_id", UUID(as_uuid=True), sa.ForeignKey("players.id")),
        sa.Column("timestamp_ms", sa.Integer, nullable=False),
        sa.Column("from_x", sa.Float, nullable=False),
        sa.Column("from_y", sa.Float, nullable=False),
        sa.Column("to_x", sa.Float, nullable=False),
        sa.Column("to_y", sa.Float, nullable=False),
        sa.Column("is_successful", sa.Boolean, default=True),
        sa.Column("is_assist", sa.Boolean, default=False),
    )
    op.create_table("possession_records",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("match_id", UUID(as_uuid=True), sa.ForeignKey("matches.id"), nullable=False),
        sa.Column("team_id", UUID(as_uuid=True), sa.ForeignKey("teams.id"), nullable=False),
        sa.Column("start_ms", sa.Integer, nullable=False),
        sa.Column("end_ms", sa.Integer, nullable=False),
        sa.Column("duration_ms", sa.Integer, nullable=False),
        sa.Column("period", sa.String(5), nullable=False),
        sa.Column("outcome", sa.String(50)),
    )


def downgrade():
    tables = [
        "possession_records", "pass_records", "heatmap_data", "player_stats",
        "lineup_entries", "lineups", "subscriptions", "subscription_plans",
        "shot_records", "player_match_stats", "match_analytics",
        "annotations", "clip_tags", "clips", "videos",
        "match_events", "matches", "cameras", "players",
        "tournaments", "seasons", "team_memberships", "teams", "users",
    ]
    for t in tables:
        op.drop_table(t)
